# Generated by Django 3.0.7 on 2020-06-25 22:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rsmdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=8)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('passing_out_year', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=200)),
                ('percent', models.CharField(max_length=150)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsmdata.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=300)),
                ('certificatio_body', models.TextField()),
                ('year', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsmdata.Employee')),
            ],
        ),
    ]
